#pragma once
#define WIN32_LEAN_AND_MEAN 
#include <windows.h>
#include <wil/com.h>
#include <wil/resource.h>
#include <wil/result.h>
#include <winrt/base.h>
#include <winrt/Windows.Foundation.h>
#include <wrl.h>
